# Generated by Django 5.0.7 on 2025-10-25 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='URL')),
                ('title_ru', models.CharField(max_length=255, verbose_name='Заголовок (Русский)')),
                ('title_uz', models.CharField(max_length=255, verbose_name='Заголовок (Узбекский)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Описание (Русский)')),
                ('description_uz', models.TextField(blank=True, verbose_name='Описание (Узбекский)')),
                ('seo_title_ru', models.CharField(blank=True, max_length=255, verbose_name='SEO заголовок (Русский)')),
                ('seo_title_uz', models.CharField(blank=True, max_length=255, verbose_name='SEO заголовок (Узбекский)')),
                ('meta_description_ru', models.CharField(blank=True, max_length=300, verbose_name='Meta описание (Русский)')),
                ('meta_description_uz', models.CharField(blank=True, max_length=300, verbose_name='Meta описание (Узбекский)')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
    ]
