# Generated by Django 5.0.7 on 2025-10-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['page_type', 'slug'], 'verbose_name': 'Страница', 'verbose_name_plural': 'Страницы'},
        ),
        migrations.AddField(
            model_name='page',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='page',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AddField(
            model_name='page',
            name='page_type',
            field=models.CharField(choices=[('home', 'Главная страница'), ('services', 'Услуги'), ('cases', 'Кейсы'), ('pricing', 'Цены'), ('contact', 'Контакты'), ('about', 'О нас'), ('custom', 'Пользовательская страница')], default='custom', help_text='Выберите тип страницы для автоматического заполнения', max_length=20, verbose_name='Тип страницы'),
        ),
        migrations.AddField(
            model_name='page',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления'),
        ),
    ]
