# Generated by Django 5.0.7 on 2025-12-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_page_telegram_url_page_linkedin_url_page_facebook_url_page_instagram_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_type',
            field=models.CharField(choices=[('home', 'Главная страница'), ('services', 'Услуги'), ('cases', 'Кейсы')], default='custom', help_text='Выберите тип страницы для автоматического заполнения', max_length=20, verbose_name='Тип страницы'),
        ),
    ]
