# Generated by Django 5.0.7 on 2025-10-25 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhyUsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(help_text='Заголовок преимущества на русском языке', max_length=200, verbose_name='Заголовок (русский)')),
                ('title_uz', models.CharField(help_text='Заголовок преимущества на узбекском языке', max_length=200, verbose_name='Заголовок (узбекский)')),
                ('description_ru', models.TextField(help_text='Подробное описание преимущества на русском языке', verbose_name='Описание (русский)')),
                ('description_uz', models.TextField(help_text='Подробное описание преимущества на узбекском языке', verbose_name='Описание (узбекский)')),
                ('icon', models.CharField(default='Award', help_text='Название иконки из Lucide React (например: Award, Users, Shield)', max_length=50, verbose_name='Иконка')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок отображения элемента (меньше число = выше в списке)', verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, help_text='Отображать ли этот элемент на сайте', verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Преимущество',
                'verbose_name_plural': 'Преимущества',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
