# Generated by Django 5.0.7 on 2025-10-25 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name_ru', models.CharField(blank=True, max_length=255, verbose_name='Название компании (Русский)')),
                ('company_name_uz', models.CharField(blank=True, max_length=255, verbose_name='Название компании (Узбекский)')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('address_ru', models.CharField(blank=True, max_length=255, verbose_name='Адрес (Русский)')),
                ('address_uz', models.CharField(blank=True, max_length=255, verbose_name='Адрес (Узбекский)')),
                ('telegram', models.CharField(blank=True, max_length=100, verbose_name='Telegram')),
            ],
            options={
                'verbose_name': 'Контакт компании',
                'verbose_name_plural': 'Контакты компании',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Имя')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
    ]
