# Generated by Django 5.0.7 on 2025-10-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=255, verbose_name='Название (Русский)')),
                ('title_uz', models.CharField(max_length=255, verbose_name='Название (Узбекский)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')),
                ('features_ru', models.TextField(help_text='Одна функция на строку (Русский)', verbose_name='Функции (Русский)')),
                ('features_uz', models.TextField(help_text='Одна функция на строку (Узбекский)', verbose_name='Функции (Узбекский)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Тарифный план',
                'verbose_name_plural': 'Тарифные планы',
                'ordering': ['order', 'id'],
            },
        ),
    ]
