# Generated by Django 5.0.7 on 2025-10-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('title_uz', models.CharField(max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('features', models.TextField(help_text='One feature per line')),
                ('features_ru', models.TextField(help_text='One feature per line', null=True)),
                ('features_uz', models.TextField(help_text='One feature per line', null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('seo_title_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('seo_title_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('meta_description_ru', models.CharField(blank=True, max_length=300, null=True)),
                ('meta_description_uz', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
