# Generated by Django 5.0.7 on 2025-10-23 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricingplan',
            name='seo_title',
        ),
        migrations.RemoveField(
            model_name='pricingplan',
            name='meta_description',
        ),
    ]
