# Generated by Django 5.0.7 on 2025-10-23 20:07

from django.db import migrations


def remove_all_pricing(apps, schema_editor):
    PricingPlan = apps.get_model('pricing', 'PricingPlan')
    PricingPlan.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_auto_20251024_0056'),
    ]

    operations = [
        migrations.RunPython(remove_all_pricing),
    ]
