# Generated by Django 5.0.7 on 2025-10-25 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=255, verbose_name='Название (Русский)')),
                ('title_uz', models.CharField(max_length=255, verbose_name='Название (Узбекский)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Описание (Русский)')),
                ('description_uz', models.TextField(blank=True, verbose_name='Описание (Узбекский)')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Подкатегория услуги',
                'verbose_name_plural': 'Подкатегории услуг',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=255, verbose_name='Название (Русский)')),
                ('title_uz', models.CharField(max_length=255, verbose_name='Название (Узбекский)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Описание (Русский)')),
                ('description_uz', models.TextField(blank=True, verbose_name='Описание (Узбекский)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Изображение')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.servicesubcategory', verbose_name='Подкатегория')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['order', 'id'],
            },
        ),
    ]
