# Generated by Django 5.0.7 on 2025-10-25 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.CharField(default='Settings', help_text='Название иконки из Lucide React', max_length=50, verbose_name='Иконка'),
        ),
    ]
