# Generated by Django 5.0.7 on 2025-10-23 20:06

from django.db import migrations


def remove_all_services(apps, schema_editor):
    Service = apps.get_model('services', 'Service')
    Service.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20251024_0055'),
    ]

    operations = [
        migrations.RunPython(remove_all_services),
    ]
