# Generated by Django 5.0.7 on 2025-10-31 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=255, verbose_name='Название (Русский)')),
                ('title_uz', models.CharField(max_length=255, verbose_name='Название (Узбекский)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Описание (Русский)')),
                ('description_uz', models.TextField(blank=True, verbose_name='Описание (Узбекский)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='workplan/', verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Этап работы',
                'verbose_name_plural': 'Этапы работы',
                'ordering': ['order', 'id'],
            },
        ),
    ]
