# Generated by Django 5.0.7 on 2025-10-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('title_uz', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(blank=True)),
                ('description_ru', models.TextField(blank=True, null=True)),
                ('description_uz', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cases/')),
                ('client', models.CharField(blank=True, max_length=255)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('seo_title_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('seo_title_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('meta_description_ru', models.CharField(blank=True, max_length=300, null=True)),
                ('meta_description_uz', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'ordering': ['-year', 'id'],
            },
        ),
    ]
