# Generated by Django 5.0.7 on 2025-10-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=255, verbose_name='Название (Русский)')),
                ('title_uz', models.CharField(max_length=255, verbose_name='Название (Узбекский)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Описание (Русский)')),
                ('description_uz', models.TextField(blank=True, verbose_name='Описание (Узбекский)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cases/', verbose_name='Изображение')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Кейс',
                'verbose_name_plural': 'Кейсы',
                'ordering': ['-created_at'],
            },
        ),
    ]
