# Generated by Django 5.0.7 on 2025-10-23 19:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='client',
        ),
        migrations.RemoveField(
            model_name='case',
            name='year',
        ),
        migrations.RemoveField(
            model_name='case',
            name='seo_title',
        ),
        migrations.RemoveField(
            model_name='case',
            name='meta_description',
        ),
        migrations.AddField(
            model_name='case',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
