# Generated by Django 5.0.7 on 2025-10-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='description_ru',
            field=models.TextField(blank=True, verbose_name='Описание (Русский)'),
        ),
        migrations.AlterField(
            model_name='case',
            name='description_uz',
            field=models.TextField(blank=True, verbose_name='Описание (Узбекский)'),
        ),
    ]
