# Generated by Django 5.0.7 on 2025-10-23 20:06

from django.db import migrations


def remove_all_cases(apps, schema_editor):
    Case = apps.get_model('cases', 'Case')
    Case.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_auto_20251024_0051'),
    ]

    operations = [
        migrations.RunPython(remove_all_cases),
    ]
