# Generated by Django 5.0.7 on 2025-10-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_ru', models.CharField(max_length=255, verbose_name='Вопрос (Русский)')),
                ('question_uz', models.CharField(max_length=255, verbose_name='Вопрос (Узбекский)')),
                ('answer_ru', models.TextField(verbose_name='Ответ (Русский)')),
                ('answer_uz', models.TextField(verbose_name='Ответ (Узбекский)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Часто задаваемый вопрос',
                'verbose_name_plural': 'Часто задаваемые вопросы',
                'ordering': ['order', 'id'],
            },
        ),
    ]
