# Generated by Django 5.0.7 on 2025-10-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('question_ru', models.CharField(max_length=255, null=True)),
                ('question_uz', models.CharField(max_length=255, null=True)),
                ('answer', models.TextField()),
                ('answer_ru', models.TextField(null=True)),
                ('answer_uz', models.TextField(null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('seo_title_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('seo_title_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('meta_description_ru', models.CharField(blank=True, max_length=300, null=True)),
                ('meta_description_uz', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
