# Generated by Django 5.0.7 on 2025-10-23 20:07

from django.db import migrations


def remove_all_faq(apps, schema_editor):
    FAQ = apps.get_model('faq', 'FAQ')
    FAQ.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_auto_20251024_0056'),
    ]

    operations = [
        migrations.RunPython(remove_all_faq),
    ]
